name: Starter Pipeline #Worflow name

on: push #trigger

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Command
        run: echo "Hello World!" > demo.txt

      - run: cat demo.txt
      - run: pwd
      - run: ls